# Generated by Django 5.0.7 on 2024-08-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_user_bookmarked_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="github",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="looking_for",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
