"""
Django settings for devmarketer_project project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import dj_database_url

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#ALSO SPECIFYED PORT. MIGHT BE A 500 ERROR FIX AS WELL. dont think so
PORT = int(os.environ.get('PORT', 8000))

SECRET_KEY = "46cfe521525b948ba0724839cbd46b9c"
#"django-insecure-^#p144u_(ev)@1ni!@#g(f_gaet@vh%fq^wc3h@+@(lq#tzma9"
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

#if you are running locally
TESTING = True

#if you want to use static (Keep false for)
NO_STATIC = False

if TESTING:
    ALLOWED_HOSTS = ['*']    
else:
    ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(" ")


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'static_file_errors': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'static_file_errors.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['static_file_errors'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}



#USED FOR TOKENS AND AUTH
AUTH_USER_MODEL = 'api.User'


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'corsheaders',
    'api',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if not TESTING:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    
ROOT_URLCONF = "devmarketer_project.urls"

#Make sure to use the react index.html template here. Edit the template to support static files. 500 fix


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'DIRS': [os.path.join(BASE_DIR, 'react_build')],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



#NAME OF THE APP
WSGI_APPLICATION = "devmarketer_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

#Testing is only after ive started using things on render
if TESTING:
    DATABASES['default'] = dj_database_url.parse("postgresql://database_1o26_user:C6Cu4rhHBqxlGQFRFxRCaz8hlPOVQaxI@dpg-cqlvfu52ng1s73e07dm0-a.oregon-postgres.render.com/database_1o26")
else:
    database_url = os.environ.get("DATABASE_URL")
    DATABASES['default'] = dj_database_url.parse(database_url)


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

if TESTING:
    if not NO_STATIC:
        print("USING REACT BUILD STATIC FILES")
        
        REACT_BUILD_DIR = os.path.join(BASE_DIR, 'react_build')

        # Direct Django to look in the React build's static directory
        STATICFILES_DIRS = [
            os.path.join(REACT_BUILD_DIR, 'static'),  # React's static files
        ]

        # If using WhiteNoise for testing, ensure these settings are correct
        STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

        WHITENOISE_USE_FINDERS = True
        WHITENOISE_MANIFEST_STRICT = False
        WHITENOISE_COMPRESS = True
        WHITENOISE_AUTOREFRESH = True

        # Point Django templates to React build output for the entry point
        TEMPLATES[0]['DIRS'] = [os.path.join(REACT_BUILD_DIR)]

    

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Allow CORS for all origins (for development purposes)
CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=500),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

